create sequence address_seq start with 1 increment by 50;
create sequence airport_seq start with 1 increment by 50;
create sequence flight_seq start with 1 increment by 50;
create sequence image_seq start with 1 increment by 50;
create sequence revinfo_seq start with 1 increment by 50;
create table address (id bigint not null, city varchar(255), country varchar(255), street varchar(255), zip varchar(255), primary key (id));
create table address_aud (rev integer not null, revtype smallint, id bigint not null, city varchar(255), country varchar(255), street varchar(255), zip varchar(255), primary key (rev, id));
create table airport (address_id bigint, id bigint not null, name varchar(20), iata varchar(255), primary key (id));
create table airport_aud (rev integer not null, revtype smallint, address_id bigint, id bigint not null, iata varchar(255), name varchar(255), primary key (rev, id));
create table airport_image_aud (rev integer not null, revtype smallint, airport_id bigint not null, id bigint not null, primary key (rev, airport_id, id));
create table airport_user (facebook_id varchar(255), password varchar(255), username varchar(255) not null, primary key (username));
create table airport_user_roles (airport_user_username varchar(255) not null, roles varchar(255));
create table flight (delay integer, id bigint not null, landing_id bigint, takeoff_id bigint, takeoff_time timestamp(6), flight_number varchar(255), primary key (id));
create table flight_aud (delay integer, rev integer not null, revtype smallint, id bigint not null, landing_id bigint, takeoff_id bigint, takeoff_time timestamp(6), flight_number varchar(255), primary key (rev, id));
create table image (airport_id bigint, id bigint not null, file_name varchar(255), data bytea, primary key (id));
create table image_aud (rev integer not null, revtype smallint, id bigint not null, file_name varchar(255), data bytea, primary key (rev, id));
create table revinfo (rev integer not null, revtstmp bigint, primary key (rev));
alter table if exists address_aud add constraint FKcc7vlgg86eqe1dmvivbkv046v foreign key (rev) references revinfo;
alter table if exists airport add constraint FKlabd5pksv56twbgly520u0fm5 foreign key (address_id) references address;
alter table if exists airport_aud add constraint FKmcli2qotv87m9hckdfqlap1p6 foreign key (rev) references revinfo;
alter table if exists airport_image_aud add constraint FK57vbhpo86af1sgnb6wifqrsc foreign key (rev) references revinfo;
alter table if exists airport_user_roles add constraint FKj9jifhxemic2jh6a7wxcefki4 foreign key (airport_user_username) references airport_user;
alter table if exists flight add constraint FKlo8um1qhyvn4ec5tt90u49g9g foreign key (landing_id) references airport;
alter table if exists flight add constraint FKnvldg0a2nu9ivpbmebljf4g1i foreign key (takeoff_id) references airport;
alter table if exists flight_aud add constraint FKhsh47yo772an5k6vlxcbnbj1a foreign key (rev) references revinfo;
alter table if exists image add constraint FKr3v11sq0fbqjqhb5xenrcob3c foreign key (airport_id) references airport;
alter table if exists image_aud add constraint FKetc5y2t13bkdk5yuj4eswagd4 foreign key (rev) references revinfo;
